# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hacker_news_url', models.URLField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('posted_on', models.DateTimeField()),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_items', models.ManyToManyField(related_name='deleted_items', to=settings.AUTH_USER_MODEL)),
                ('read_items', models.ManyToManyField(related_name='read_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
