# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDataItem',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_open_price', models.FloatField()),
                ('stock_close_price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('stock_adj_close', models.FloatField()),
                ('stock_volume', models.FloatField()),
                ('stock_low_price', models.FloatField()),
                ('stock_high_price', models.FloatField()),
                ('stock_date', models.DateTimeField()),
            ],
        ),
    ]
