# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_data', '0002_auto_20160925_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedataitem',
            name='stock_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
